"""Generate the DeepSeek Harness bundle package from the canonical plugin
sources (#530).

Route, settled by #529: the plugin's DSH surface ships as a DSH **bundle
package** — a directory whose ``package.json`` declares ``dsh.bundle.patch`` —
added once by a person with::

    dsh plugin --profile <profile> add <absolute path to the bundle>

The bundle exists because DSH reads no ``.claude-plugin/plugin.json`` and has
no marketplace manifest. Its patch is ONE top-level ``insert:`` entry appending
four rows to the profile's composed root — the only patch form that appends new
top-level rows:

- a **new** ``@deepseek-ai/dsh-skill-filesystem`` provider carrying
  ``customSkillDirs`` pointed at the plugin's ``skills/``, so the eight skills
  are discovered without restructuring (DSH discovers ``<root>/<name>/SKILL.md``
  one level deep, exactly the plugin's layout). It is an insert rather than an
  ``id``-targeted config override because ``dsh-web-app`` disables the host
  ``skill-filesystem`` row, and a config override on a disabled row does
  nothing.
- three ``@deepseek-ai/dsh-tool-subagent`` rows, one per canonical agent file in
  ``agents/``, because DSH has no filesystem markdown-agent loader and each
  delegation tool carries one fixed persona, tool filter and depth cap.

The patch bakes in an **absolute** plugin root — ``customSkillDirs`` is
``resolve()``d against the DSH *boot* cwd, so a relative value is not an option
— which is why the patch is generated on demand and gitignored rather than
committed. Re-run it after moving the plugin checkout. The committed half is
``package.json`` alone: it carries no plugin-derived value, so nothing here
joins ``scripts/release.sh`` or CI's freshness guard.

Translation rules, mirroring ``generate-opencode.py``:

- ``name`` becomes the model-facing ``toolName``. Kebab-case is kept (the
  agent's own name) rather than DSH's snake_case house style, so the skills'
  prose keeps naming one handle across hosts.
- ``tools:`` becomes ``toolFilter.allow``, mapped onto DSH's global tool names.
  It is an allow-list because the CC frontmatter is one.
- ``skills:`` preload is dropped — a DSH child joins its parent's composition,
  so there is no per-child skill preload — and the body's "preloaded above"
  claims become instructions to load the skill on demand, the same rewrite the
  OpenCode generator makes.
- ``model:`` is deliberately *not* translated: the Claude Code tier split
  (sonnet judgement / haiku comprehension) is the host's routing concern, and
  all three rows default to the ``deepseek-flash`` route (#528).
- ``maxDepth: 1``: a wiki subagent delegates no further, and the ``spawn``
  provider enforces the cap.

No skill file is read or rewritten — the per-skill docs branch owns how a skill
addresses the binary, and ``skills/`` enters the patch as a directory path only.
The agent bodies are the one canonical content translated, which is this
script's "stay in step with the canonical sources" contract.

CLI::

    python generate-dsh-bundle.py [--plugin-root DIR] [--bundle DIR]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from io import StringIO
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import LiteralScalarString

#: Canonical Claude Code agent files, plugin-relative — one DSH delegation tool
#: each. Mirrors generate-opencode.py's CANONICAL_AGENTS; keep in sync.
CANONICAL_AGENTS = ("wiki-ingest.md", "wiki-linter.md", "wiki-researcher.md")

#: The generated patch's filename, and the path ``package.json`` must declare.
PATCH_FILENAME = "cordis.patch.yml"

#: The bundle's committed manifest. The generator validates it rather than
#: writing it: it is durable source, and nothing in it derives from the plugin.
MANIFEST_FILENAME = "package.json"

#: Marks a patch file as this script's output, so a re-run recognises its own
#: file and refuses to clobber one it did not write. Also the banner's first
#: line, so detection and attribution are the same string.
GENERATED_MARKER = "Generated by wiki-plugin/scripts/generate-dsh-bundle.py"

#: Row ids are namespaced by the plugin, so they cannot collide with a
#: host-level or another bundle's row.
ROW_ID_PREFIX = "wiki-knowledge"

#: Plugin package names the inserted rows mount.
SKILL_PROVIDER_PACKAGE = "@deepseek-ai/dsh-skill-filesystem"
SUBAGENT_TOOL_PACKAGE = "@deepseek-ai/dsh-tool-subagent"

#: A distinct provider name for the inserted skill provider. Hygiene, not a
#: requirement: skill providers merge by skill name, nearest layer winning, so
#: a distinct name only keeps the composition readable.
SKILL_PROVIDER_NAME = "wiki-knowledge"

#: The route every DSH wiki subagent defaults to (#528). Not derived from the
#: CC ``model:`` frontmatter — see the module docstring.
DEFAULT_ROUTE = {"provider": "deepseek-official", "model": "deepseek-flash"}

#: A wiki subagent delegates no further; the ``spawn`` provider enforces the
#: cap, so the delegation tool stays visible and runtime policy owns rejection.
SUBAGENT_MAX_DEPTH = 1

#: Claude Code tool name -> DSH global tool name. The global names are what
#: ``toolFilter`` admits; an unmapped CC tool is a generation error rather than
#: a silently dropped capability.
CC_TOOL_TO_DSH = {
    "Read": "read",
    "Write": "write",
    "Edit": "edit",
    "Grep": "grep",
    "Glob": "glob",
    "Bash": "bash",
}

#: The CC "skill preloaded above" claim, which is false on DSH — a child joins
#: its parent's composition and loads a skill on demand, never into its own
#: context. The ``per``/``using`` lead-in is left in place so the rewrite reads
#: as a sentence, not a splice. Same rule as generate-opencode.py.
_PRELOAD_RE = re.compile(r"`([a-z0-9-]+)` skill( procedure)? preloaded above")


class GenerationError(RuntimeError):
    """Raised when a canonical source can't be translated faithfully."""


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split CC markdown into ``(frontmatter_yaml, body)``.

    The frontmatter is the leading block between two ``---`` lines; the body is
    everything after. Raises :class:`ValueError` when there is no frontmatter
    block. Duplicated from generate-opencode.py rather than imported: both are
    standalone person-run scripts, and neither is importable by name (hyphen).
    """
    if not text.startswith("---\n"):
        raise ValueError("no YAML frontmatter block at the start of the file")
    closing = text.find("\n---\n", 4)
    if closing == -1:
        raise ValueError("unterminated YAML frontmatter block")
    return text[4:closing], text[closing + 5 :]


def parse_frontmatter(yaml_text: str) -> dict:
    """Parse the CC frontmatter YAML into a plain dict."""
    return YAML(typ="safe").load(yaml_text)


def translate_body(body: str) -> str:
    """Rewrite the CC preload claims in an agent body for DSH.

    On CC a skill is injected into the subagent's context and the body says so;
    on DSH the child shares the parent's skill catalog and must read the skill
    itself, so the claim becomes a load instruction. Everything else is carried
    through verbatim.
    """
    return _PRELOAD_RE.sub(
        r"`\1` skill\2 — load the `\1` skill and follow its procedure", body,
    )


def agent_row(frontmatter: dict, body: str) -> dict:
    """Build one ``dsh-tool-subagent`` row from a canonical agent file.

    ``name`` becomes the ``toolName`` (per-instance, and every loaded instance
    must use a distinct one), ``tools:`` becomes the child's allow-list, the
    translated body becomes the ``persona``, and the row id is namespaced by the
    plugin. ``modelSelectionSettings`` is deliberately absent — left false,
    because a standing ``modelSelectionSettings`` throws when the row is not
    inside a preset.
    Raises :class:`GenerationError` on anything the translation can't represent
    faithfully (no name, no tools, an unknown CC tool).
    """
    name = frontmatter.get("name")
    if not name:
        raise GenerationError("agent frontmatter carries no name")

    tools = frontmatter.get("tools")
    if not tools:
        raise GenerationError(f"{name}: no tools in frontmatter")
    allow: list[str] = []
    for tool in (t.strip() for t in str(tools).split(",")):
        if not tool:
            continue
        if tool not in CC_TOOL_TO_DSH:
            raise GenerationError(
                f"{name}: no DSH global tool name for CC tool {tool!r}"
            )
        if CC_TOOL_TO_DSH[tool] not in allow:
            allow.append(CC_TOOL_TO_DSH[tool])

    return {
        "id": f"{ROW_ID_PREFIX}-agent-{name}",
        "name": SUBAGENT_TOOL_PACKAGE,
        "config": {
            "provider": "spawn",
            "toolName": name,
            "agentOptions": dict(DEFAULT_ROUTE),
            "persona": translate_body(body).strip(),
            "toolFilter": {"allow": allow},
            "maxDepth": SUBAGENT_MAX_DEPTH,
        },
    }


def skill_provider_row(plugin_root: Path) -> dict:
    """The inserted skill provider row, pointing at the plugin's ``skills/``.

    The directory is a *path*, never the skill bodies: the per-skill prose owns
    how a skill addresses the binary, and nothing here reads a SKILL.md.
    """
    return {
        "id": f"{ROW_ID_PREFIX}-skill-filesystem",
        "name": SKILL_PROVIDER_PACKAGE,
        "config": {
            "providerName": SKILL_PROVIDER_NAME,
            "customSkillDirs": [str(plugin_root / "skills")],
        },
    }


def discover_skills(skills_dir: Path) -> list[str]:
    """The skill names DSH will discover under ``skills_dir``, sorted.

    DSH's filesystem provider discovers ``<root>/<name>/SKILL.md`` one level
    deep, which is exactly the plugin's layout, so the names are derived from
    the tree rather than from a hand-kept list that could drift. Raises
    :class:`GenerationError` when the directory is absent or holds no skill —
    either means ``--plugin-root`` points somewhere that is not the plugin, and
    a silently empty catalog is the worst outcome.
    """
    if not skills_dir.is_dir():
        raise GenerationError(f"skills directory not found: {skills_dir}")
    names = sorted(path.parent.name for path in skills_dir.glob("*/SKILL.md"))
    if not names:
        raise GenerationError(f"no <name>/SKILL.md found under {skills_dir}")
    return names


def build_patch(plugin_root: Path, agents: list[tuple[dict, str]]) -> list[dict]:
    """The whole patch: one ``insert:`` entry, skill provider first then one row
    per agent file in ``CANONICAL_AGENTS`` order.
    """
    insert = [skill_provider_row(plugin_root)]
    insert.extend(agent_row(frontmatter, body) for frontmatter, body in agents)
    return [{"insert": insert}]


def _literalize(value: object) -> object:
    """Recursively turn every multi-line string into a literal block scalar.

    The personas are paragraphs of prose; ruamel's default for a plain ``str``
    with newlines is a double-quoted single line full of ``\\n`` escapes, which
    is correct but unreadable in a file a person is expected to inspect. A
    literal block is the same string, laid out as written. A string a literal
    block cannot hold (a trailing newline, a first line that starts with a
    space) still round-trips — ruamel picks a chomping or indentation indicator,
    or falls back to quoting.
    """
    if isinstance(value, str) and "\n" in value:
        return LiteralScalarString(value)
    if isinstance(value, dict):
        return {key: _literalize(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_literalize(item) for item in value]
    return value


def render_patch(patch: list[dict], plugin_root: Path, skills: list[str]) -> str:
    """Render the patch as the bundle's ``cordis.patch.yml``.

    Prefixed with the generated-file banner that :func:`generate` uses as its
    own-file marker, and carrying the plugin root and the discovered skills so a
    reader can see what the absolute path resolved to without running anything.
    Lines are never folded (``width``), matching ADR-0024's posture for emitted
    files, and multi-line scalars are block scalars, so the personas read as
    prose rather than as escapes.
    """
    banner = [
        f"# {GENERATED_MARKER} — DO NOT EDIT BY HAND.",
        "# Regenerate: python wiki-plugin/scripts/generate-dsh-bundle.py",
        f"# Plugin root: {plugin_root}",
        f"# Skills discovered: {', '.join(skills)}",
        "#",
        "# One insert appending four rows to the profile's composed root: a new",
        "# skill provider carrying customSkillDirs, then one dsh-tool-subagent row",
        "# per canonical agent file. Installed by path — see the bundle's README.",
    ]
    yaml = YAML()
    yaml.width = 4096
    # The patch is a bare top-level sequence, and ruamel indents a root sequence
    # by `offset`. Shift the whole document back to column 0 so it opens on
    # `- insert:`, the shape the bundle patches DSH ships are written in; a
    # uniform shift cannot change what the YAML means.
    root_offset = 2
    yaml.indent(mapping=2, sequence=4, offset=root_offset)
    stream = StringIO()
    yaml.dump(_literalize(patch), stream)
    body = "".join(
        line[root_offset:] if line.startswith(" " * root_offset) else line
        for line in stream.getvalue().splitlines(keepends=True)
    )
    return "\n".join(banner) + "\n" + body


def _read_canonical(path: Path, what: str) -> str:
    """Read a canonical source file, raising :class:`GenerationError` with a
    clear message when it's absent — generation must never silently skip a
    source it is supposed to translate."""
    if not path.is_file():
        raise GenerationError(f"{what} not found: {path}")
    return path.read_text(encoding="utf-8")


def _guard_unmanaged(target: Path) -> None:
    """Refuse to overwrite a patch file this script did not generate.

    Re-running the generator against its own output is safe and writes identical
    bytes; a hand-authored file at the same path is not ours to clobber, and a
    reader who put one there should hear about it rather than lose it.
    """
    if not target.exists():
        return
    if GENERATED_MARKER not in target.read_text(encoding="utf-8"):
        raise GenerationError(
            f"{target} exists but was not generated by this script; move it "
            "aside or delete it, then re-run"
        )


def _guard_manifest(bundle_dir: Path) -> None:
    """The bundle's committed manifest must be present and must declare the
    patch file this script writes — DSH fails loud at boot on a bundle that
    declares no ``dsh.bundle`` patch, and failing here names the real problem.
    """
    manifest_path = bundle_dir / MANIFEST_FILENAME
    if not manifest_path.is_file():
        raise GenerationError(
            f"bundle manifest not found: {manifest_path} (the generator writes "
            "only the patch; package.json is committed source)"
        )
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise GenerationError(f"{manifest_path} is not valid JSON: {exc}") from exc
    declared = (manifest.get("dsh") or {}).get("bundle", {}).get("patch")
    if declared != f"./{PATCH_FILENAME}":
        raise GenerationError(
            f"{manifest_path} must declare dsh.bundle.patch as "
            f"'./{PATCH_FILENAME}', found {declared!r}"
        )


def generate(plugin_root: Path | str, bundle_dir: Path | str) -> list[Path]:
    """Generate the bundle's patch into ``bundle_dir``.

    Reads the canonical agents and resolves the skill directory from
    ``plugin_root``; validates the bundle's committed manifest; writes
    ``<bundle_dir>/cordis.patch.yml`` and returns the paths written. Calling
    twice with the same inputs writes identical bytes (idempotent). Errors on
    any missing canonical source rather than silently skipping it.
    """
    root = Path(plugin_root).resolve()
    out = Path(bundle_dir).resolve()

    skills = discover_skills(root / "skills")

    agents: list[tuple[dict, str]] = []
    for filename in CANONICAL_AGENTS:
        text = _read_canonical(root / "agents" / filename, "canonical agent file")
        yaml_text, body = split_frontmatter(text)
        frontmatter = parse_frontmatter(yaml_text)
        if not frontmatter.get("name"):
            raise GenerationError(f"canonical agent {filename} carries no name")
        agents.append((frontmatter, body))

    patch = build_patch(root, agents)
    text = render_patch(patch, root, skills)

    # Every guard runs before the directory is created, so a bad --plugin-root
    # or a missing manifest leaves no new directory behind.
    _guard_manifest(out)
    target = out / PATCH_FILENAME
    _guard_unmanaged(target)
    out.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return [target]


def _next_steps(bundle_dir: Path) -> str:
    """The install output: the one command a person runs, the restart, and the
    one host capability this bundle does not carry.

    The restart is not optional — a profile's bundle list is read once at boot,
    and adding a bundle is exactly what the install does, so ``patchReload``
    does not help here.

    The note is the user-facing half of #534: the plugin's hooks are not ported,
    so a DSH session has no tool-call log, and both readers of that log behave
    accordingly. Stated at install time because the installing person is who
    will later look for the cost summary.
    """
    return (
        "\nnext:\n"
        f"  dsh plugin --profile <profile> add {bundle_dir}\n"
        "  then restart dsh — the profile's bundle list is read once at boot\n"
        "\nnote: no hooks are installed — DSH keeps its own session log under\n"
        "  $DSH_HOME/sessions/, so `enchiridion tool-call-stats` has nothing to\n"
        "  summarise here and `enchiridion ingest` prints no cost summary (see\n"
        "  the bundle README)\n"
    )


def main(argv: list[str] | None = None) -> int:  # pragma: no cover - thin CLI
    parser = argparse.ArgumentParser(
        description="Generate the DeepSeek Harness bundle package's patch from "
        "the canonical plugin sources.",
    )
    parser.add_argument(
        "--plugin-root",
        default=str(Path(__file__).resolve().parent.parent),
        help="the plugin's install directory (defaults to this script's own "
        "plugin, so a bare run generates from the plugin source itself)",
    )
    parser.add_argument(
        "--bundle",
        default=None,
        help="the bundle directory to write into (defaults to "
        "<plugin-root>/wiring/dsh)",
    )
    args = parser.parse_args(argv)

    root = Path(args.plugin_root).resolve()
    bundle_dir = Path(args.bundle).resolve() if args.bundle else root / "wiring" / "dsh"

    try:
        written = generate(root, bundle_dir)
    except (GenerationError, ValueError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    for path in written:
        print(path)
    print(_next_steps(bundle_dir), end="")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
